name = "fadyhikone"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"
compatibility_flags = ["nodejs_compat"]

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "fadyhikone-production"
database_id = "3c41910c-1b96-47ad-99e7-604df7428bdb"
migrations_dir = "migrations"
